name: graphann
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - flake8
  - pylint
  - black
  - nbconvert
  - pdftotext
